spring:
    application:
        name: qingketang
    profiles:
        active: dev
    datasource:
        url: jdbc:mysql://localhost:3306/qingketang?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password:
    graphql:
        schema:
            printer:
                enabled: true
        path: /graphql
server:
    port: 8081

management:
    endpoints:
        web:
            exposure:
                include: health,metrics,info
